stages:
  - static_analysis
  - build_n_test

variables:
  PROJECT_NAME: ports-of-call
  ENABLE_CDASH: false

include:
 - .gitlab/common.yml


########
# Jobs #
########

openmpi_gcc:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  variables:
    SPACK_ENV_NAME: openmpi-gcc

openmpi_cuda_gcc_volta:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  variables:
    SPACK_ENV_NAME: openmpi-cuda-gcc-volta
    SCHEDULER_PARAMETERS: "-N 1 --qos=debug -p volta-x86 -C cpu_family:haswell --time=02:00:00"

openmpi_cuda_gcc_ampere:
  extends: [.ascgit_job, .darwin_job, .build_and_test]
  variables:
    SPACK_ENV_NAME: openmpi-cuda-gcc-ampere
    SCHEDULER_PARAMETERS: "-N 1 --qos=debug -p shared-gpu-ampere"

rzvernal_craympich_rocm_mi250_gcc:
  extends: [.ascgit_job, .rzadams_job, .rzvernal_regular_job, .build_and_test]
  variables:
    SPACK_ENV_NAME: craympich-rocm-gfx90a-gcc

rzadams_craympich_rocm_mi300_gcc:
  extends: [.ascgit_job, .rzadams_job, .rzadams_regular_job, .build_and_test]
  variables:
    SPACK_ENV_NAME: craympich-rocm-gfx942-gcc
