name: Tests minimal

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    tests:
      name: Minimal test suite
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            submodules: recursive
        - name: Set system to non-interactive mode
          run: export DEBIAN_FRONTEND=noninteractive
        - name: install dependencies
          run: |
            sudo apt-get install -y --force-yes -qq build-essential
        - name: build and install
          run: |
            mkdir -p buld
            cd build
            cmake -DPORTS_OF_CALL_BUILD_TESTING=ON ..
            make -j
            make test
